# the sequencing adapter
adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index
  index: "data/ref/index"
  # gtf file with transcripts
  annotation: "data/ref/annotation.chr21.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated

params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""
  deseq2:
    threads: 1
