# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config_complex/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config_complex/units.tsv


ref:
  # Ensembl species name
  species: saccharomyces_cerevisiae
  # Ensembl release
  release: 100
  # Genome build
  build: R64-1-1


trimming:
  activate: False

mergeReads:
  activate: False

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # variables where you are interested in whether they have
  # an effect on expression levels
  variables_of_interest:
    treatment_1:
      # any fold change will be relative to this factor level
      base_level: untreated
    treatment_2:
      # any fold change will be relative to this factor level
      base_level: untreated
  batch_effects:
    - jointly_handled
  # contrasts for the deseq2 results method to determine fold changes
  contrasts:
    treatment_1_alone:
      # must be one of the variables_of_interest
      variable_of_interest: treament_1
      # the variable's level to test against the base_level
      level_of_interest: treated
    treatment_2_alone:
      # must be one of the variables_of_interest
      variable_of_interest: treament_2
      # the variable's level to test against the base_level
      level_of_interest: treated
    both_treatments: 'list(c("treatment_1_treated_vs_untreated", "treatment_2_treated_vs_untreated", "treatment_2treated.treatment_1treated"))'
  # The default model includes all interactions among variables_of_interest,
  # and batch_effects added on. For the example above this implicitly is:
  # model: ~jointly_handled + treatment_1 * treatment_2
  # For the default model to be used, simply specify an empty `model: ""` below.
  # If you want to introduce different assumptions into your model, you can
  # specify a different model to use, for example skipping the interaction:
  # model: ~jointly_handled + treatment_1 + treatment_2
  model: ""

params:
  cutadapt-pe: ""
  cutadapt-se: ""
  star: ""
