# For a fully commented config.yaml file, see the main `config/config.yaml`
# example file.

samples: config_sra/samples.tsv
# This data comes from:
# * https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1359129
# * https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA1359129&o=acc_s%3Aa
units: config_sra/units.tsv


ref:
  species: saccharomyces_cerevisiae
  release: 115
  build: R64-1-1


trimming:
  activate: True

mergeReads:
  activate: False

pca:
  activate: True
  labels:
    - treatment

diffexp:
  variables_of_interest:
    medium:
      base_level: glycerol
  batch_effects: ""
  contrasts:
    trehalose_vs_glycerol:
      variable_of_interest: medium
      level_of_interest: trehalose
  model: ~medium

params:
  star:
    index: ""
    align: ""
