# For a fully commented config.yaml file, see the main `config/config.yaml`
# example file.

samples: config_sra/samples.tsv
# This data comes from:
# * https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1269045
# * https://doi.org/10.7554/eLife.107157.3
units: config_sra/units.tsv


ref:
  species: saccharomyces_cerevisiae
  release: 115
  build: R64-1-1


trimming:
  activate: True

mergeReads:
  activate: False

pca:
  activate: True
  labels:
    - treatment

diffexp:
  variables_of_interest:
    mutational_status:
      base_level: wildtype
  batch_effects: ""
  contrasts:
    apj1d_vs_wildtype:
      variable_of_interest: mutational_status
      level_of_interest: apj1d
  model: ~mutational_status

params:
  star:
    index: ""
    align: ""
