$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  trimming:
    type: object
    properties:
      skip:
        type: boolean
      adapter:
        type: string
        pattern: "^[ACGT]+$"

  ref:
    type: object
    properties:
      index:
        type: string
      annotation:
        type: string
    required:
      - index
      - annotation

  pca:
    type: object
    properties:
      labels:
        type: array
        items:
          type: string
    required:
      - labels

  diffexp:
    type: object

  params:
    type: object
    properties:
      star:
        type: string
      cutadapt-se:
        type: string
      cutadapt-pe:
        type: string
    required:
      - star
      - cutadapt-se
      - cutadapt-pe

required:
  - samples
  - units
  - trimming
  - ref
  - pca
  - diffexp
  - params
